---
title: "Restrictions Shiny App"
output: html_document
---

```{r}
# Load packages
library(tidyverse)
library(dplyr)
library(igraph)
library(visNetwork)
library(ggnetwork)
library(grDevices)
```

```{r}
# Load network datasets
restaurants_final <- read.csv("wrangled_csv_data/restaurants_network_data.csv")
bars_final <- read.csv("wrangled_csv_data/bars_network_data.csv")
mask_mandates_final <- read.csv("wrangled_csv_data/mask_mandates_network_data.csv")
gathering_bans_final <- read.csv("wrangled_csv_data/gathering_bans_network_data.csv")
stay_at_home_orders_final <- read.csv("wrangled_csv_data/stay_at_home_orders_network_data.csv")
```

```{r}
# create igraph object
states <- c("AK", "CT", "SD", "AR", "LA")

gathering_bans_final <- gathering_bans_final %>%
  filter(state_one %in% states,
         state_two %in% states) %>%
  select(-X)
         #gathering_bans_overLap > 10)

gathering_bans_final <- as.matrix.data.frame(gathering_bans_final)

gathering_bans_igraph <- graph_from_data_frame(gathering_bans_final, directed = FALSE)

#gatbans <- ggnetwork(gathering_bans_igraph)
#head(gatbans)

# create visualization of this network
# ggplot(data = gatbans, aes(x = x, y = y, 
#           xend = xend, yend = yend)) +
#  geom_edges(arrow = arrow(type = "closed", length = unit(8, "pt")),
#     color = "lightgray") +
#  geom_nodes() +
#  geom_nodelabel(aes(label = name)) +
#  theme_blank()

# igraph <- set_vertex_attr(gathering_bans_igraph, "overlap", value = gathering_bans_network$overLap)
# # Graph network
# ggnetwork(igraph) %>%
# ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
# geom_edges(color = "lightgray", curvature = .2) +
# geom_nodes(aes(size = overLap)) +
# geom_nodelabel_repel(aes(label = name)) +
# labs(size = "PageRank") +
# theme_blank()
# 

gathering_bans_visNetwork <- toVisNetworkData(gathering_bans_igraph)

#  visIgraphLayout(layout = "layout_in_circle") %>%



eigScalePal <- colorRampPalette(c("blue", "red"), bias = 5)

x <- c(0.01, 0.2, 0.03, 0.05, 0.05)

edges <- gathering_bans_visNetwork$edges
nodes <- gathering_bans_visNetwork$nodes %>%
  mutate(covid_case = as.numeric(x),
        color = eigScalePal(5)[cut(covid_case, breaks = 5)]) %>%
  select(-covid_case)
 
#eigen_centrality(gathering_bans_igraph)
# eigScalePal <- colorRampPalette(c("blue", "red"), bias = 1)
# nodes$color <- eigScalePal(5)[cut(eigen_centrality(gathering_bans_igraph)$vector, breaks = 5)]

edges <- edges %>%
  mutate(value = as.numeric(edges$gathering_bans_overLap),
         width = value/100) %>%
  select(-value)


# # data.frame from edges legend
# ledges <- data.frame(Color = edges$color,
#                      Label = edges$color)

visNetwork(nodes, edges, height = "700px", width = "100%", 
           main = list(text = "Network for States Sharing the Same COVID Restrictions in 2020", 
                       style = "font-family:Arial;font-size:20px"
                       ),
           submain = list(text = 
           "*Nodes are colored by proportion of annual COVID cases per state population<br>
           *Edges are weighted by number of days in 2020 that states shared 
                                  the same restrictions",
           style = "font-family:Arial;font-size:13px")) %>%
  visNodes(size = 10) %>%
  visOptions(selectedBy = "group", 
             highlightNearest = list(enabled = TRUE, hover = TRUE), 
             nodesIdSelection = TRUE) %>%
  visPhysics(stabilization = FALSE) %>%
  visEdges(color = list(color = "black", highlight = "red")) 

# create legend for node color
legend_image <- as.raster(matrix(eigScalePal(5), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Proportion of COVID cases')
text(x=1.5, y = seq(0,1,l=5), labels = seq(0,1,l=5))
rasterImage(legend_image, 0, 0, 1,1)
```